### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by ValdikSS** [ValdikSS/hoogmoon-testing#1]
* [ ] Separate curl built with OpenSSL, to "test as a desktop" in conditions with TLS fingerprinting
* [ ] curl with HTTP3 support
* [ ] curl with openssl largepadding
* [ ] Package zapret + LAN redirection rules
* [ ] Switch to OpenWrt 23.05 (dnsmasq filter_aaaa and other changes)
